<script src="<?php SERVERURL;?>public/js/menu.js"></script>
<script src="<?php SERVERURL;?>public/js/main.js"></script>
<script src="<?php SERVERURL;?>public/js/alertas.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://unpkg.com/@popperjs/core@2"></script>
<script src="<?php SERVERURL;?>public/js/data_config.js"></script>
<script src="<?php SERVERURL;?>public/js/datatables.js"></script>